INSERT INTO product_ent (id, name, manufacturer, price) values (1, 'Care','Lifebuoy','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (2, 'Nature','Lifebuoy','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (3, 'Lemon Fresh','Lifebuoy','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (4, 'Vita Protect','Lifebuoy','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (5, 'Moisture Plus','Lifebuoy','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (6, 'Original','Cinthol','Godrej Group');
INSERT INTO product_ent (id, name, manufacturer, price) values (7, 'Cool','Cinthol','Godrej Group');
INSERT INTO product_ent (id, name, manufacturer, price) values (8, 'Deo','Cinthol','Godrej Group');
INSERT INTO product_ent (id, name, manufacturer, price) values (9, 'Lime','Cinthol','Godrej Group');
INSERT INTO product_ent (id, name, manufacturer, price) values (10, 'Confidence','Cinthol','Godrej Group');
INSERT INTO product_ent (id, name, manufacturer, price) values (11, 'Original','Dettol','Reckitt Benckiser');
INSERT INTO product_ent (id, name, manufacturer, price) values (12, 'Skincare','Dettol','Reckitt Benckiser');
INSERT INTO product_ent (id, name, manufacturer, price) values (13, 'Cool','Dettol','Reckitt Benckiser');
INSERT INTO product_ent (id, name, manufacturer, price) values (14, 'VELVET TOUCH','Lux','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (15, 'SOFT TOUCH','Lux','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (16, 'CHARMING MAGNOLIA','Lux','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (17, 'HYPNOTIC ROSE','Lux','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (18, 'ICONIC IRIS','Lux','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (19, 'FRESH SPLASH','Lux','Unilever');
INSERT INTO product_ent (id, name, manufacturer, price) values (20, 'CREAMY PERFECTION','Lux','Unilever');